apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-service
  template:
    metadata:
      labels:
        app: add-service
    spec:
      containers:
        - name: add-service
          image: bitprj/add-service
          ports:
            - containerPort: 31337
          env:
            - name: UPLOAD_ENDPOINT
              value: https://ab612311c912a41ce89b70d7db4e70c4-84380695.us-east-2.elb.amazonaws.com
            - name: EMAIL_ENDPOINT
              value: https://a77eb6879980e4732befb1ccdd4365e3-1987684319.us-east-2.elb.amazonaws.com
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  selector:
    app: add-service
  ports:
    - port: 80
      targetPort: 31337
  type: LoadBalancer