apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-service
  template:
    metadata:
      labels:
        app: fetch-service
    spec:
      containers:
        - name: fetch-service
          image: bitprj/fetch-service
          ports:
            - containerPort: 1337
          env:
            - name: HOST
              value: babieswithhats.coqtasittblb.us-east-2.rds.amazonaws.com
            - name: PASSWORD
              value: x7CRPKg&t&^F
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: fetch-service
spec:
  selector:
    app: fetch-service
  ports:
    - port: 80
      targetPort: 1337
  type: LoadBalancer