apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: bitprj/gateway-service
          ports:
            - containerPort: 4444
          env:
            - name: FETCH_ENDPOINT
              value: https://a6929fbbfd2404ed8962c91eea394d35-1854050381.us-east-2.elb.amazonaws.com
            - name: ADD_ENDPOINT
              value: https://a26ba46e907944fdf926b73f74f0358d-526249480.us-east-2.elb.amazonaws.com
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - port: 80
      targetPort: 4444
  type: LoadBalancer