version: '3'

services:
    redis:
        image: redislabs/rejson:latest
        container_name: redis.redisshoppingcart.docker2
        restart: unless-stopped
        environment:
            REDIS_PASSWORD: 11954
        command: redis-server --loadmodule "/usr/lib/redis/modules/rejson.so" --requirepass "$REDIS_PASSWORD"
        ports:
            - 127.0.0.1:${REDIS_PORT}:6379
        networks:
            - global
networks:
    global:
        external: true
