name: Build Minikube TinyHats

on:
  push:
    branches:
      - 'no-s3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Frontend Service
        uses: docker/build-push-action@v2
        with:
          context: services/frontend-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-frontend-service
      - name: Gateway Service
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-gateway-service
      - name: Admin Service
        uses: docker/build-push-action@v2
        with:
          context: services/admin-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-admin-service
      - name: Add Service
        uses: docker/build-push-action@v2
        with:
          context: services/add-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-add-service
      - name: Fetch Service
        uses: docker/build-push-action@v2
        with:
          context: services/fetch-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-fetch-service
      - name: Manipulation Service
        uses: docker/build-push-action@v2
        with:
          context: services/manipulation-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-manipulation-service
      - name: Moderate Service
        uses: docker/build-push-action@v2
        with:
          context: services/moderate-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-moderate-service
      - name: Upload Service
        uses: docker/build-push-action@v2
        with:
          context: services/upload-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/mini-upload-service