name: upload-service production

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - services/upload-service/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Upload Service
        uses: docker/build-push-action@v2
        with:
          context: services/upload-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bitprj/tinyhat-upload-service:latest
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Assume Role
        uses: youyo/awscredswrap@v1
        with:
          role_arn: ${{ secrets.ROLE_ARN }}
          duration_seconds: 3600
          role_session_name: 'awscredswrap@GitHubActions'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'
          
      - name: Identity Check
        run: aws sts get-caller-identity
          
      - name: Apply Configuration Changes
        uses: bitprj/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f kube

      - name: Trigger deploy
        uses: bitprj/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: -n default rollout restart deploy

      - name: Slack notification                                
        uses: rtCamp/action-slack-notify@master                 
        env:                                                    
          SLACK_CHANNEL: 'k8s-work'                  
          SLACK_MESSAGE: 'Just deployed upload-service to production!'
          SLACK_TITLE: 'Deploy'                         
          SLACK_USERNAME: 'Ganning'                           
          SLACK_ICON: "https://ca.slack-edge.com/TJ2FB5CE9-U024KSA4HFE-636d36515d0a-512"
          SLACK_COLOR: '#228B22'                                
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}       
          MSG_MINIMAL: true  